### ISSUE TITLE
PXD-854 ⁃ update() does not behave correctly

### ISSUE THREAD

**Issue by phuongph** [uc-cdis/indexd#139]
The problem is when we update current urls, and urls_metadata.

```
client = IndexClient()
docs = client.get("40a395b0-51d1-426e-9fbd-13a91ac7547e")
new_url = "s3://host_name/bucket/key_name"
docs.urls.append(new_url)
docs.urls_metadata[new_url] = {"state": "validated"}

docs.patch()
```

The error I get is:
`requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR`

The `inded-error.log` are:
```
[Thu Jun 21 20:25:00.331227 2018] [:error] [pid 8685:tid 140451114325760] [2018-06-21 20:25:00,327][    indexd][  ERROR] Exception on /index/40a395b0-51d1-426e-9fbd-13a91ac7547e [PUT]
[Thu Jun 21 20:25:00.331269 2018] [:error] [pid 8685:tid 140451114325760] Traceback (most recent call last):
[Thu Jun 21 20:25:00.331277 2018] [:error] [pid 8685:tid 140451114325760]   File "/var/tungsten/services/indexd/deploy/current/venv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
[Thu Jun 21 20:25:00.331285 2018] [:error] [pid 8685:tid 140451114325760]     response = self.full_dispatch_request()
[Thu Jun 21 20:25:00.331293 2018] [:error] [pid 8685:tid 140451114325760]   File "/var/tungsten/services/indexd/deploy/current/venv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
[Thu Jun 21 20:25:00.331301 2018] [:error] [pid 8685:tid 140451114325760]     rv = self.handle_user_exception(e)
[Thu Jun 21 20:25:00.331308 2018] [:error] [pid 8685:tid 140451114325760]   File "/var/tungsten/services/indexd/deploy/current/venv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
[Thu Jun 21 20:25:00.331317 2018] [:error] [pid 8685:tid 140451114325760]     reraise(exc_type, exc_value, tb)
[Thu Jun 21 20:25:00.331324 2018] [:error] [pid 8685:tid 140451114325760]   File "/var/tungsten/services/indexd/deploy/current/venv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
[Thu Jun 21 20:25:00.331333 2018] [:error] [pid 8685:tid 140451114325760]     rv = self.dispatch_request()
[Thu Jun 21 20:25:00.331340 2018] [:error] [pid 8685:tid 140451114325760]   File "/var/tungsten/services/indexd/deploy/current/venv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
[Thu Jun 21 20:25:00.331348 2018] [:error] [pid 8685:tid 140451114325760]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Jun 21 20:25:00.331356 2018] [:error] [pid 8685:tid 140451114325760]   File "/var/tungsten/services/indexd/deploy/current/venv/lib/python2.7/site-packages/indexd-0.1-py2.7.egg/indexd/auth/__init__.py", line 24, in check_auth
[Thu Jun 21 20:25:00.331364 2018] [:error] [pid 8685:tid 140451114325760]     return f(*args, **kwargs)
[Thu Jun 21 20:25:00.331371 2018] [:error] [pid 8685:tid 140451114325760]   File "/var/tungsten/services/indexd/deploy/current/venv/lib/python2.7/site-packages/indexd-0.1-py2.7.egg/indexd/index/blueprint.py", line 280, in put_index_record
[Thu Jun 21 20:25:00.331380 2018] [:error] [pid 8685:tid 140451114325760]     urls_metadata=urls_metadata,
[Thu Jun 21 20:25:00.331387 2018] [:error] [pid 8685:tid 140451114325760]   File "/var/tungsten/services/indexd/deploy/current/venv/lib/python2.7/site-packages/indexd-0.1-py2.7.egg/indexd/index/drivers/alchemy.py", line 599, in update
[Thu Jun 21 20:25:00.331395 2018] [:error] [pid 8685:tid 140451114325760]     session.add(record)
[Thu Jun 21 20:25:00.331402 2018] [:error] [pid 8685:tid 140451114325760]   File "/var/tungsten/services/indexd/deploy/current/venv/lib/python2.7/site-packages/SQLAlchemy-1.0.8-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1577, in add
[Thu Jun 21 20:25:00.331421 2018] [:error] [pid 8685:tid 140451114325760]     self._save_or_update_state(state)
[Thu Jun 21 20:25:00.331429 2018] [:error] [pid 8685:tid 140451114325760]   File "/var/tungsten/services/indexd/deploy/current/venv/lib/python2.7/site-packages/SQLAlchemy-1.0.8-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1596, in _save_or_update_state
[Thu Jun 21 20:25:00.331437 2018] [:error] [pid 8685:tid 140451114325760]     self._save_or_update_impl(st_)
[Thu Jun 21 20:25:00.331443 2018] [:error] [pid 8685:tid 140451114325760]   File "/var/tungsten/services/indexd/deploy/current/venv/lib/python2.7/site-packages/SQLAlchemy-1.0.8-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1846, in _save_or_update_impl
[Thu Jun 21 20:25:00.331451 2018] [:error] [pid 8685:tid 140451114325760]     self._update_impl(state)
[Thu Jun 21 20:25:00.331458 2018] [:error] [pid 8685:tid 140451114325760]   File "/var/tungsten/services/indexd/deploy/current/venv/lib/python2.7/site-packages/SQLAlchemy-1.0.8-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1832, in _update_impl
[Thu Jun 21 20:25:00.331466 2018] [:error] [pid 8685:tid 140451114325760]     state_str(state)
[Thu Jun 21 20:25:00.331472 2018] [:error] [pid 8685:tid 140451114325760] InvalidRequestError: Instance '<IndexRecordUrl at 0x7fbd432f53d0>' has been deleted.  Use the make_transient() function to send this object back to the transient state.
```

**Comment by phuongph** [comment]
Maybe it's helpful
https://stackoverflow.com/questions/5033547/sqlalchemy-cascade-delete

**Comment by philloooo** [comment]
➤ Trevar Simmons commented:

[~phillis.tt@gmail.com], can you help us understand how the link about deleting parents while the children persist is relevant to Phuong's error message?

Does he need to delete something in the way described in that link before updating?

**Comment by philloooo** [comment]
➤ Phuong Pham commented:

I think the problem is from my cluster, the IndexClient for some reason is not upgraded to the latest version. When I delete all virtual environment and run the setup again, the bug does not happen.
